import { ExternalLink, Globe2, MapPin, Phone, Star } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { WebsiteStatusBadge } from "./statuses";
import { externalUrl, getDomain } from "@/lib/utils";

export default function LeadDetails({ lead }) {
  return <div className="space-y-5 animate-fade-up">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><h1 className="text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">{lead.businessName}</h1><p className="mt-1 text-sm text-slate-500">{lead.category} · {lead.city}, {lead.state}</p></div><div className="flex flex-col gap-2 sm:flex-row">{lead.google.mapsUrl && <a href={lead.google.mapsUrl} target="_blank" rel="noopener noreferrer"><Button variant="outline" className="w-full sm:w-auto"><MapPin className="h-4 w-4" />Open Google Maps</Button></a>}{lead.website.exists && <a href={externalUrl(lead.website.url)} target="_blank" rel="noopener noreferrer"><Button variant="primary" className="w-full sm:w-auto"><ExternalLink className="h-4 w-4" />Visit Website</Button></a>}</div></div>
    <div className="grid gap-5 lg:grid-cols-2">
      <Card className="card-hover"><div className="border-b p-5"><h2 className="font-semibold">Business Information</h2></div><div className="grid gap-5 p-5 sm:grid-cols-2"><Info label="Business Name" value={lead.businessName}/><Info label="Category" value={lead.category}/><Info label="Phone" value={lead.contact.phone} icon={Phone}/><Info label="Address" value={lead.address}/><Info label="City" value={lead.city}/><Info label="State" value={lead.state}/><Info label="Country" value={lead.country}/></div></Card>
      <Card className="card-hover"><div className="border-b p-5"><h2 className="font-semibold">Google Business Profile</h2></div><div className="space-y-5 p-5">{lead.google.profileExists ? <><Info label="Profile" value="Found" badge/><div className="grid grid-cols-2 gap-4"><Info label="Rating" value={lead.google.rating} icon={Star}/><Info label="Business Status" value={lead.google.businessStatus || "Operational"}/></div>{lead.google.mapsUrl && <a href={lead.google.mapsUrl} target="_blank" rel="noopener noreferrer" className="inline-flex text-sm font-medium text-blue-600 hover:underline">Open Maps <ExternalLink className="ml-1 h-3.5 w-3.5"/></a>}</> : <Info label="Profile" value="Not Found" badge/>}</div></Card>
      <Card className="card-hover lg:col-span-2"><div className="border-b p-5"><div className="flex items-center gap-2"><Globe2 className="h-4 w-4 text-blue-600"/><h2 className="font-semibold">Website</h2></div></div><div className="grid gap-5 p-5 sm:grid-cols-2 lg:grid-cols-4">{lead.website.exists ? <><Info label="Website" value="Found" badge/><Info label="URL" value={getDomain(lead.website.url)} link={lead.website.url}/><div><p className="text-xs font-medium text-slate-400">Status</p><div className="mt-1"><WebsiteStatusBadge website={lead.website}/></div></div><Info label="HTTPS" value={lead.website.https ? "Yes" : "No"}/></> : <div className="sm:col-span-2"><Info label="Website" value="No website detected" badge/></div>}</div></Card>
    </div>
  </div>;
}
function Info({label,value,icon:Icon,badge,link}){return <div><p className="text-xs font-medium text-slate-400">{label}</p>{link?<a href={link} target="_blank" rel="noopener noreferrer" className="mt-1 inline-flex max-w-full items-center gap-1 text-sm font-medium text-blue-600 hover:underline"><span className="truncate">{value}</span><ExternalLink className="h-3 w-3 shrink-0"/></a>:<p className="mt-1 flex items-center gap-1.5 text-sm font-medium text-slate-700">{Icon&&<Icon className="h-3.5 w-3.5 text-slate-400"/>}{badge?<Badge variant={value==="Found"?"success":"default"}>{value}</Badge>:value||"—"}</p>}</div>}
