"use client";
import { useState } from "react";
import { Bell, Building2, CreditCard, User } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
export default function Settings(){const [saved,setSaved]=useState(false);return <div className="mx-auto max-w-5xl"><div className="mb-6"><h1 className="text-2xl font-bold">Settings</h1><p className="mt-1 text-sm text-slate-500">Manage your profile, workspace, usage, and preferences.</p></div><div className="grid gap-5"><Section icon={User} title="Profile" description="Personal account details"><div className="grid gap-4 md:grid-cols-2"><Field label="Full name" value="Jordan Davis"/><Field label="Email" value="jordan@example.com"/></div></Section><Section icon={Building2} title="Workspace" description="Workspace configuration"><Field label="Workspace name" value="Acme Growth"/></Section><Section icon={CreditCard} title="Usage" description="Current workspace usage"><div className="grid gap-3 sm:grid-cols-3"><Usage label="Searches" value="24 / 100"/><Usage label="Leads" value="2,450 / 5,000"/><Usage label="Exports" value="18 / 50"/></div></Section><Section icon={Bell} title="Preferences" description="Notification settings"><label className="flex items-center gap-3 text-sm"><input type="checkbox" defaultChecked className="h-4 w-4 rounded border-slate-300 text-blue-600"/>Email me when a search is complete</label><label className="mt-3 flex items-center gap-3 text-sm"><input type="checkbox" defaultChecked className="h-4 w-4 rounded border-slate-300 text-blue-600"/>Notify me about export completion</label></Section><div className="flex justify-end"><Button variant="primary" onClick={()=>{setSaved(true);setTimeout(()=>setSaved(false),2000)}}>{saved?"Saved":"Save changes"}</Button></div></div></div>}
function Section({icon:Icon,title,description,children}){return <Card><div className="border-b p-5"><div className="flex items-center gap-3"><div className="rounded-lg bg-slate-100 p-2"><Icon className="h-4 w-4 text-slate-600"/></div><div><h2 className="font-semibold">{title}</h2><p className="text-xs text-slate-500">{description}</p></div></div></div><div className="p-5">{children}</div></Card>}
function Field({label,value}){return <label className="block"><span className="mb-1.5 block text-xs font-medium text-slate-500">{label}</span><Input defaultValue={value}/></label>}
function Usage({label,value}){return <div className="rounded-xl border bg-slate-50 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>}
