"use client";
import { useState } from "react";
import { Download, FileSpreadsheet, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import ExportModal from "@/components/exports/ExportModal";
import { Toast } from "@/components/ui/toast";
const rows=[["Barbers USA","50 leads","CSV","Today","Completed"],["Dentists Texas","30 leads","Excel","Yesterday","Completed"],["Restaurants California","100 leads","CSV","Sep 8, 2026","Completed"]];
export default function Exports(){const [open,setOpen]=useState(false);const [toast,setToast]=useState("");return <div className="mx-auto max-w-6xl"><div className="mb-5 flex items-end justify-between"><div><h1 className="text-2xl font-bold">Exports</h1><p className="mt-1 text-sm text-slate-500">Download and track previous lead exports.</p></div><Button variant="primary" onClick={()=>setOpen(true)}><Download className="h-4 w-4"/>New Export</Button></div><Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500"><tr>{["Export","Search","Number of Leads","Format","Created","Status"].map(x=><th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t text-sm"><td className="px-5 py-4 font-medium">Export {String(i+1).padStart(3,"0")}</td><td className="px-5 py-4">{r[0]}</td><td className="px-5 py-4">{r[1]}</td><td className="px-5 py-4"><span className="inline-flex items-center gap-2">{r[2]==="CSV"?<FileText className="h-4 w-4 text-slate-400"/>:<FileSpreadsheet className="h-4 w-4 text-slate-400"/>}{r[2]}</span></td><td className="px-5 py-4 text-slate-500">{r[3]}</td><td className="px-5 py-4"><span className="text-xs font-semibold text-emerald-600">● {r[4]}</span></td></tr>)}</tbody></table></div></Card><ExportModal open={open} onClose={()=>setOpen(false)} onDone={setToast}/><Toast message={toast} onClose={()=>setToast("")}/></div>}
